name: bit_convert
description: Convert datatypes on a bit like level (int and String for now)
version: 0.1.3
homepage: https://bitbot.eu

environment:
  sdk: '>=2.17.0-182.2.beta <4.0.0'

dependencies:
  test_builder_annotation:
    git:
      url: https://github.com/Marc-R2/test_builder.git
      path: packages/test_builder_annotation

dev_dependencies:
  mutation_test: ^1.3.1
  test: ^1.21.4
  test_builder:
    git:
      url: https://github.com/Marc-R2/test_builder.git
      path: packages/test_builder
  very_good_analysis: ^3.0.1
