name: bit_convert
description: Convert datatypes on a bit like level (int and String for now)
version: 0.1.3
homepage: https://bitbot.eu

environment:
  sdk: '>=2.17.0-182.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.4
  very_good_analysis: ^3.0.1
